apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-pvc
  namespace: shared-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-db
  namespace: shared-services
spec:
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      serviceAccountName: shared-svc-accnt
      securityContext:
        runAsUser: 70
        supplementalGroups: [999, 1000]
        fsGroup: 70
      volumes:
        - name: postgresql-db-vol
          persistentVolumeClaim:
            claimName: postgresql-db-pvc
      containers:
        - name: postgres
          image: postgres:14-alpine
          imagePullPolicy: Never # or IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-db-vol
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: topsekret
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-db
  namespace: shared-services
spec:
  selector:
    app: postgresql-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30000
  type: NodePort
